"""empty message

Revision ID: 17b3e23d2acd
Revises: 96615b18968e
Create Date: 2022-09-24 10:49:29.426610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b3e23d2acd'
down_revision = '96615b18968e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'daily_plan', ['id'])
    op.create_unique_constraint(None, 'meal', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meal', type_='unique')
    op.drop_constraint(None, 'daily_plan', type_='unique')
    # ### end Alembic commands ###
