"""empty message

Revision ID: af57cd4c54b7
Revises: 5604462caeb5
Create Date: 2022-09-27 18:02:30.413729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af57cd4c54b7'
down_revision = '5604462caeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'daily_plan', ['id'])
    op.drop_constraint('meal_name_key', 'meal', type_='unique')
    op.create_unique_constraint(None, 'meal', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meal', type_='unique')
    op.create_unique_constraint('meal_name_key', 'meal', ['name'])
    op.drop_constraint(None, 'daily_plan', type_='unique')
    # ### end Alembic commands ###
