"""empty message

<<<<<<<< HEAD:migrations/versions/c9211f0012f8_.py
Revision ID: c9211f0012f8
Revises: 
Create Date: 2022-09-26 20:22:27.217239
========
Revision ID: cc260ead2097
Revises: 
Create Date: 2022-09-26 20:12:54.738979
>>>>>>>> 711b5ea3395720e620217b295e79087241c5abdd:migrations/versions/cc260ead2097_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/c9211f0012f8_.py
revision = 'c9211f0012f8'
========
revision = 'cc260ead2097'
>>>>>>>> 711b5ea3395720e620217b295e79087241c5abdd:migrations/versions/cc260ead2097_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
<<<<<<<< HEAD:migrations/versions/c9211f0012f8_.py
    sa.Column('sumarize', sa.String(length=120), nullable=False),
    sa.Column('nutrients', sa.String(length=80), nullable=False),
    sa.Column('ingredients', sa.String(length=80), nullable=False),
========
    sa.Column('sumarize', sa.String(length=120), nullable=True),
    sa.Column('nutrients', sa.String(length=80), nullable=True),
    sa.Column('ingredients', sa.String(length=80), nullable=True),
>>>>>>>> 711b5ea3395720e620217b295e79087241c5abdd:migrations/versions/cc260ead2097_.py
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('daily_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('first_block',
    sa.Column('daily_plan_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plan.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], )
    )
    op.create_table('second_block',
    sa.Column('daily_plan_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plan.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], )
    )
    op.create_table('third_block',
    sa.Column('daily_plan_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plan.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('third_block')
    op.drop_table('second_block')
    op.drop_table('first_block')
    op.drop_table('meal')
    op.drop_table('daily_plan')
    op.drop_table('user')
    # ### end Alembic commands ###
