"""empty message

Revision ID: dd85ee4d86c5
Revises: 923b078da462
Create Date: 2022-09-26 15:19:05.068535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd85ee4d86c5'
down_revision = '923b078da462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'daily_plan', ['id'])
    op.create_unique_constraint(None, 'meal', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meal', type_='unique')
    op.drop_constraint(None, 'daily_plan', type_='unique')
    # ### end Alembic commands ###
