"""empty message

Revision ID: fbc97238bd4b
Revises: bb4ab359322e
Create Date: 2022-09-21 19:15:31.918634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc97238bd4b'
down_revision = 'bb4ab359322e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'daily_plan', ['id'])
    op.create_unique_constraint(None, 'meal', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meal', type_='unique')
    op.drop_constraint(None, 'daily_plan', type_='unique')
    # ### end Alembic commands ###
